<?php die("Access Denied"); ?>#x#a:5:{s:4:"body";s:8894:"

<div class="item-page clearfix">


<!-- Article -->
<article itemscope itemtype="http://schema.org/Article">
	<meta itemprop="inLanguage" content="en-GB" />

	
<header class="article-header clearfix">
	<h1 class="article-title" itemprop="name">
					Pulmonary and Sleep Associates Selects Persivia Chronic Care Management 			<meta itemprop="url" content="http://persivia.com/news-events/284-pulmonary-and-sleep-associates-selects-persivia-chronic-care-management" />
			</h1>

			</header>

<!-- Aside -->
<aside class="article-aside clearfix">
    	<dl class="article-info  muted">

		
			<dt class="article-info-term">
													Details							</dt>

			
			
			
					
												<dd class="create">
					<i class="fa fa-calendar"></i>
					<time datetime="2015-12-10T02:38:00+00:00" itemprop="dateCreated">
						Created: 10 December 2015					</time>
			</dd>			
			
						</dl>
    
  </aside>  
<!-- //Aside -->




	

	

	
	
	<section class="article-content clearfix" itemprop="articleBody">
		
<p><i>Persivia’s Comprehensive Care Management Software and Services Used to Meet the Requirements for the CMS CCM Program</i> </p>
<p>LOWELL, MA, December 10, 2015 -- Persivia, a provider of real-time quality and care management solutions, today announced that Pulmonary and Sleep Associates (PSA) of Huntsville has selected <a href="index.php?option=com_content&amp;view=article&amp;id=270&amp;Itemid=847" target="_blank">Persivia Chronic Care Management</a> (Persivia CCM) to help them deliver the services required by the new CMS CPT code 99490. PSA will use the Persivia solution to increase engagement with patients for better management of chronic diseases. The Persivia CCM solution ties clinical decision support together with both quality and care management in order to provide actionable, real-time, evidence-based care management to improve overall patient care. </p>
<p>“We were looking for a comprehensive chronic care management solution that truly impacts the care of our patients,” said Theresa Campbell, practice manager of Pulmonary and Sleep Associates of Huntsville. “Persivia is the only vendor that integrates clinical decision support and chronic care management at the point of care which will positively impact our patients overall chronic care management. The additional revenue generated by the CMS CCM program is an added bonus for the practice.” </p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center">“In the post-acute environment, one of the largest factors impacting the quality of care is the variation in the standard of care,” said Mansoor Khan, Sc.D., CEO of Persivia. “Persivia Chronic Care Management builds on quality and weaves clinical intelligence into every aspect of patient care, including dynamic assessments, goals, and care gap alerts.  The solution is built upon our clinical decision support system, the industry’s largest evidence-based rule set, embedded in a real-time rules engine.” </p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center"> </p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center">Persivia CCM is based on highly configurable clinical workflow tools that provide both functional interoperability with EHRs, as well as semantic interoperability across medical terminologies. As a result, the rules editor can provide meaningful recommendations at the point of care which allows for the analysis of key data elements that are required for managing chronic care patients. Persivia CCM is not just another PHR masquerading as a care management platform.</p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center"> </p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center">Also of note, Persivia will soon be releasing a <a title="Persivia Bundled Payment Manager" href="index.php?option=com_content&amp;view=article&amp;id=283&amp;Itemid=861" target="_blank">Bundled Payment Management and Analytics</a> solution to support the <a title="CMS" href="https://innovation.cms.gov/initiatives/cjr" target="_blank">CMS Comprehensive Care in Joint Replacement</a> (CCJR) model when it becomes effective on April 1, 2016. This solution will allow organizations to <a title="CCJR Winter Conference" href="http://www.ccjr.com" target="_blank">manage bundled payments</a> throughout the year so there are no surprises during the end-of-year reconciliation with CMS.</p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center"> </p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center">About Persivia</p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center">Persivia is a real-time, secure, cloud-based information technology provider transforming healthcare by introducing clinical intelligence into care management. Persivia is dedicated to providing the healthcare industry with cutting-edge quality and chronic care management solutions. Our solutions are designed to help organizations streamline their operations, mitigate risks, and improve quality of care. Persivia delivers intelligent and actionable information that can help to improve patient care, enable better care coordination and provide innovative approaches to clinical analytics and population health. Our customers include hospitals, healthcare providers, payers, EHR vendors, systems integrators and government entities. Learn more at <a href="http://www.persivia.com/" target="_blank">www.persivia.com</a>.</p>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt -2.9pt; line-height: normal; text-align: left; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;" align="center">###</p>
<p> </p>
<p class="MsoNormal" style="margin-bottom: .0001pt; line-height: normal;"><b><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif;">Media Contact:</span></b></p>
<p>Kristin O’Neill</p>
<p>Marketing Director</p>
<p>Persivia</p>
<p>978-856-4519</p>
<p><span id="cloak79697">This email address is being protected from spambots. You need JavaScript enabled to view it.</span><script type='text/javascript'>
 //<!--
 document.getElementById('cloak79697').innerHTML = '';
 var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
 var path = 'hr' + 'ef' + '=';
 var addy79697 = 'kr&#105;st&#105;n.&#111;n&#101;&#105;ll' + '&#64;';
 addy79697 = addy79697 + 'p&#101;rs&#105;v&#105;&#97;' + '&#46;' + 'c&#111;m';
 var addy_text79697 = 'm&#97;&#105;lt&#111;:kr&#105;st&#105;n.&#111;n&#101;&#105;ll@p&#101;rs&#105;v&#105;&#97;.c&#111;m';
 document.getElementById('cloak79697').innerHTML += '<a ' + path + '\'' + prefix + ':' + addy79697 + '\'>'+addy_text79697+'<\/a>';
 //-->
 </script></p>	</section>
	
  <!-- footer -->
    <!-- //footer -->

	
	
	
</article>
<!-- //Article -->


</div>";s:4:"head";a:11:{s:5:"title";s:83:"Pulmonary and Sleep Associates Selects Persivia Chronic Care Management  - Persivia";s:11:"description";N;s:4:"link";s:0:"";s:8:"metaTags";a:2:{s:10:"http-equiv";a:1:{s:12:"content-type";s:24:"text/html; charset=utf-8";}s:8:"standard";a:2:{s:8:"keywords";s:126:"clinical decision support medication management infection control population health management quality healthcare chronic care";s:6:"rights";N;}}s:5:"links";a:1:{s:50:"http://persivia.com/news-events?catid=0&amp;id=284";a:3:{s:8:"relation";s:9:"canonical";s:7:"relType";s:3:"rel";s:7:"attribs";a:0:{}}}s:11:"styleSheets";a:1:{s:53:"/plugins/content/jadisqus_debate_echo/asset/style.css";a:3:{s:4:"mime";s:8:"text/css";s:5:"media";N;s:7:"attribs";a:0:{}}}s:5:"style";a:0:{}s:7:"scripts";a:8:{s:33:"/media/system/js/mootools-core.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:24:"/media/system/js/core.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:33:"/media/system/js/mootools-more.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:27:"/media/jui/js/jquery.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:34:"/media/jui/js/jquery-noconflict.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:35:"/media/jui/js/jquery-migrate.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:27:"/media/system/js/caption.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}s:30:"/media/jui/js/bootstrap.min.js";a:3:{s:4:"mime";s:15:"text/javascript";s:5:"defer";b:0;s:5:"async";b:0;}}s:6:"script";a:1:{s:15:"text/javascript";s:576:"
var disqus_shortname = 'jademo-light';
var disqus_config = function(){
	this.language = 'en';
};
window.addEvent('load', function(){
	(function () {
	  var s = document.createElement('script'); s.async = true;
	  s.src = '//jademo-light.disqus.com/count.js';
	  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(s);
	}());
});
jQuery(window).on('load',  function() {
				new JCaption('img.caption');
			});jQuery(document).ready(function(){
	jQuery('.hasTooltip').tooltip({"html": true,"container": "body"});
});";}s:6:"custom";a:0:{}s:10:"scriptText";a:0:{}}s:13:"mime_encoding";s:9:"text/html";s:7:"pathway";a:2:{i:0;O:8:"stdClass":2:{s:4:"name";s:13:"News & Events";s:4:"link";s:72:"index.php?option=com_content&view=category&layout=blog&id=114&Itemid=783";}i:1;O:8:"stdClass":2:{s:4:"name";s:72:"Pulmonary and Sleep Associates Selects Persivia Chronic Care Management ";s:4:"link";s:0:"";}}s:6:"module";a:0:{}}